os: Visual Studio 2015

version: 0.4.{build}

install:
- ps: .\Source\Scripts\CI.InstallSystemPrereqs.ps1

build_script:
- ps: .\CI Build

test: off

cache:
  - .\psake.4.4.2
  - .\src\packages -> .\src\Hero.Toolbox.Tests.Unit\packages.config
